name: Make

on:
  workflow_dispatch:
    inputs:
      vid_url:
        description: 'The URL to process'
        required: true
      cmd:
        description: 'Command'
        required: true
      postback:
        description: 'Postback Url'
        required: true


jobs:
  process-vid:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Vid
      run: |
        wget -v -O input.mp4 ${{ github.event.inputs.vid_url }}

    - uses: FedericoCarboni/setup-ffmpeg@v3
      id: setup-ffmpeg
      with:
        ffmpeg-version: release
        architecture: ''
        github-token: ${{ github.server_url == 'https://github.com' && github.token || '' }}

    - name: Process Vid
      run: ${{ github.event.inputs.cmd }}

    - name: Upload to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: video-artifact
        path: output.mp4
    
    - name: Send notification
      run: |
        ARTIFACT_URL="https://github.com/${{ github.repository }}/suites/${{ github.run_id }}/artifacts"
        curl -X POST -H "Content-Type: application/json" -d "{\"artifact_url\": \"${ARTIFACT_URL}\"}" https://webhook.site/767759ac-ade3-41ea-9ca8-5c28a003dad0

    # - name: Upload Vid to Node.js Server
    #   run: |
    #     curl -X POST ${{ github.event.inputs.postback }} \
    #     -F 'file=@output.mp4'